package com.example.f1service.constant

class F1DriverNumber {
    val maxURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MAXVER01.png.transform/2col/image.png"
    val sergioURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SERPER01.png.transform/2col/image.png"
    val charlesURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CHALEC01.png.transform/2col/image.png"
    val georgeURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GEORUS01.png.transform/2col/image.png"
    val sainzURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CARSAI01.png.transform/2col/image.png"
    val lewisURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LEWHAM01.png.transform/2col/image.png"
    val norrisURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANNOR01.png.transform/2col/image.png"
    val bottasURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/VALBOT01.png.transform/2col/image.png"
    val oconURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ESTOCO01.png.transform/2col/image.png"
    val pierreURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/PIEGAS01.png.transform/2col/image.png"
    val alonsoURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/FERALO01.png.transform/2col/image.png"
    val magnussenURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/KEVMAG01.png.transform/2col/image.png"
    val danielURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/DANRIC01.png.transform/2col/image.png"
    val vettelURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SEBVET01.png.transform/2col/image.png"
    val yukiURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/YUKTSU01.png.transform/2col/image.png"
    val alexAlbonURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ALEALB01.png.transform/2col/image.png"
    val lanceURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANSTR01.png.transform/2col/image.png"
    val zhouURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GUAZHO01.png.transform/2col/image.png"
    val mickURL = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MICSCH02.png.transform/2col/image.png"
    val goat = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICLAF01.png.transform/2col/image.png"
    val nico = "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICHUL01.png.transform/2col/image.png"
}